In [1]:
import pandas as pd

class_data = pd.read_csv("/kaggle/input/zoo-animal-classification/class.csv")
zoo_data = pd.read_csv("/kaggle/input/zoo-animal-classification/zoo.csv")
X = zoo_data.iloc[:, :-1].values
y = zoo_data.iloc[:, -1].values
zoo_data.head(10)

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   
5     buffalo     1         0     0     1         0        0         0   
6        calf     1         0     0     1         0        0         0   
7        carp     0         0     1     0         0        1         0   
8     catfish     0         0     1     0         0        1         1   
9        cavy     1         0     0     1         0        0         0   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   
5        1         1         1         0     0     4     1         0        1   
6        1         1         1         0     0     4     1         1        1   
7        1         1         0         0     1     0     1         1        0   
8        1         1         0         0     1     0     1         0        0   
9        1         1         1         0     0     4     0         1        0   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1  
5           1  
6           1  
7           4  
8           4  
9           1

In [2]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
zoo_data['animal_name_encoded'] = le.fit_transform(zoo_data['animal_name'])

In [3]:
frequency = zoo_data['animal_name'].value_counts()
zoo_data['animal_name_encoded'] = zoo_data['animal_name'].map(frequency)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [5]:
from sklearn.preprocessing import StandardScaler

# If X_train and X_test are numpy arrays, they need to be sliced 
X_train_scaled = X_train[:, 1:]  
X_test_scaled = X_test[:, 1:]    


sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train_scaled)
X_test_scaled = sc.transform(X_test_scaled)

In [6]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100, criterion = 'entropy', random_state = 0)
classifier.fit(X_train_scaled, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test_scaled)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[7 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 5 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 2]]


1.0

In [8]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, X=X_train_scaled, y=y_train, cv=10)
print(f"Cross-validation mean accuracy: {accuracies.mean()}")
print(f"Cross-validation std deviation: {accuracies.std()}")

/opt/conda/lib/python3.10/site-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  warnings.warn(


Cross-validation mean accuracy: 0.9375
Cross-validation std deviation: 0.10077822185373188
